# Generated by Django 2.2.3 on 2019-07-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('git_page', models.TextField(verbose_name='Git Page')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='빈칸으로 두면 자동으로 입력됩니다', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('job_objective', models.CharField(max_length=10, verbose_name='Job Objective')),
                ('qualifications', models.TextField(blank=True, verbose_name='Qualifications')),
                ('work_experience', models.TextField(blank=True, verbose_name='Work Experience')),
                ('education', models.TextField(blank=True, verbose_name='Education')),
                ('military_service', models.TextField(blank=True, verbose_name='Military Service')),
                ('hobby', models.TextField(blank=True, verbose_name='Hobby')),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('level', models.IntegerField(verbose_name='Level')),
                ('projects', models.ManyToManyField(to='introduction.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='techs',
            field=models.ManyToManyField(to='introduction.Tech'),
        ),
    ]
