# Generated by Django 2.2.3 on 2019-07-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0003_auto_20190711_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='자동으로 기입되니 입력하지 않으셔도 됩니다.', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
