# Generated by Django 2.2.3 on 2019-08-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0004_auto_20190711_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='projects',
        ),
        migrations.AlterField(
            model_name='project',
            name='techs',
            field=models.ManyToManyField(related_name='projects', to='introduction.Tech'),
        ),
    ]
