# Generated by Django 2.2.3 on 2019-08-24 05:55

import board.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0005_auto_20190823_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=board.fields.ThumbnailImageField(blank=True, null=True, upload_to='photo/%Y/%m'),
        ),
    ]
