# Generated by Django 2.2.3 on 2019-08-24 06:23

import board.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0006_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=board.fields.ThumbnailImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
