# Generated by Django 2.2.3 on 2019-08-24 06:26

import board.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0007_auto_20190824_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=board.fields.ThumbnailImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
