# Generated by Django 2.2.3 on 2019-08-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0008_auto_20190824_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.TextField(blank=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='resume',
            name='git_addr',
            field=models.TextField(blank=True, verbose_name='GitAddr'),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.TextField(blank=True, verbose_name='Phone'),
        ),
    ]
