# Generated by Django 2.2.3 on 2019-07-13 05:43

import board.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_album_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=board.fields.ThumbnailImageField(null=True, upload_to='photo/%Y/%m'),
        ),
    ]
