# Generated by Django 2.2.3 on 2019-08-16 06:23

import board.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20190813_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=board.fields.ThumbnailImageField(blank=True, null=True, upload_to='photo/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Board'),
        ),
        migrations.AlterField(
            model_name='like',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board'),
        ),
    ]
